---
title: "Contador"
author: "[2026]"
output: 
  flexdashboard::flex_dashboard:
    logo: lacto_logo_fondo.png
    orientation: rows
    vertical_layout: scroll
    theme:
      bootswatch: united   #tema predeterminado
      navbar-bg: "#1D0A70"  #Color barra de navegación
    css: estilo_contador.css

---



```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tibble) 
library(forcats)
library(tidyr)
library(purrr)
library(stringr)
library(scales)
library(lubridate)
library(readxl)
library(highcharter)
library(ggplot2)
library(gtsummary)
library(reactable)
library(reactablefmtr)
library(htmltools)
library(htmlwidgets)
library(plotly)
library(crosstalk)
library(bslib)
library(sass)
library(bsicons)
library(googlesheets4)
library(gargle)

#3 lineas para agregar commas a highcharts
hcoptslang <- getOption("highcharter.lang")
hcoptslang$thousandsSep <- ","
options(highcharter.lang = hcoptslang)

#Auth   ------------------------------------------------------
try(gs4_auth(
  path = secret_decrypt_json(
    "gs4_encuestas_serviceaccount_enc.json",
    key = "GS4_ENCUESTAS_KEY"
  )
))


#Importación   --------------------------------------------------------
# data <- read_sheet("1jdtuSyTAYUH1drZDpKhyVM7OLlNfz-UiaWxhNPN0MII")
# principal <- read_sheet("1QHoMDBYt3PIum25vvC7LSkb0mexLSRACJW-kgg9zols")
data1 <- read_sheet("1_TXKJTVLJiq1Pn2g2sEg0W8YPViTvKfwLzPRisGyfu8") %>%  #El Salvador
  mutate(pais = "El Salvador",
         fecha = `Submitted at`- hours(6)) %>% 
  relocate(pais, .before = `Submitted at`) %>% 
  relocate(fecha, .after = `Submitted at`) %>% 
  rename("area1" = `A. ¿A qué dirección perteneces?`,
         "area2" = `B. ¿A qué departamento perteneces?`,
         "area3" = `C. ¿A qué área de trabajo perteneces?`,
         "area4" = `D. ¿A qué lugar de trabajo perteneces?`) %>% 
  mutate(`1. ¿Existen acciones o prácticas en Lactolac que contribuyan a una mejor cultura laboral? Comparte ejemplos` = as.character(`1. ¿Existen acciones o prácticas en Lactolac que contribuyan a una mejor cultura laboral? Comparte ejemplos`),
         `2. ¿Qué recomendaría para mejorar algún aspecto de la cultura laboral? Comparte ejemplos` = as.character(`2. ¿Qué recomendaría para mejorar algún aspecto de la cultura laboral? Comparte ejemplos`),
         `Respondent ID`= as.character(`Respondent ID`))
  
data2 <- read_sheet("1dHIWxjF396Xbx9I-pRzjsi8_card23Ere5YTEhZIR44") %>%   #Guatemala
  mutate(pais = "Guatemala",
         fecha = `Submitted at`- hours(6)) %>% 
  relocate(pais, .before = `Submitted at`) %>% 
  relocate(fecha, .after = `Submitted at`) %>% 
  rename("area1" = `A. ¿A qué dirección perteneces?`,
         "area3" = `B. ¿A qué área de trabajo perteneces?`,
         "area4" = `C. ¿A qué lugar de trabajo perteneces?`) %>% 
  mutate(area2 = NA) %>% 
  relocate(area2,.after = area1) %>% 
  mutate(`1. ¿Existen acciones o prácticas en Lactolac que contribuyan a una mejor cultura laboral? Comparte ejemplos` = as.character(`1. ¿Existen acciones o prácticas en Lactolac que contribuyan a una mejor cultura laboral? Comparte ejemplos`),
         `2. ¿Qué recomendaría para mejorar algún aspecto de la cultura laboral? Comparte ejemplos` = as.character(`2. ¿Qué recomendaría para mejorar algún aspecto de la cultura laboral? Comparte ejemplos`))

data3 <- read_sheet("14T4qo89Rsf0UYTCFY23q-IE-tFq9utfYY2zOA6nijVE") %>%   #Honduras
  mutate(pais = "Honduras",
         fecha = `Submitted at`- hours(6)) %>% 
  relocate(pais, .before = `Submitted at`) %>% 
  relocate(fecha, .after = `Submitted at`) %>% 
  rename("area1" = `A. ¿A qué dirección perteneces?`,
         "area3" = `B. ¿A qué área de trabajo perteneces?`,
         "area4" = `C. ¿A qué lugar de trabajo perteneces?`) %>% 
  mutate(area2 = NA) %>% 
  relocate(area2,.after = area1)

data4 <- read_sheet("1RKGlMXP_NPAbD_O5FyC3FCqRLBgzkQfnhLyVtxscw8A") %>%   #Nicaragua
  mutate(pais = "Nicaragua",
         fecha = `Submitted at`- hours(6)) %>% 
  relocate(pais, .before = `Submitted at`) %>% 
  relocate(fecha, .after = `Submitted at`) %>% 
  rename("area1" = `A. ¿A qué dirección perteneces?`,
         "area3" = `B. ¿A qué área de trabajo perteneces?`,
         "area4" = `C. ¿A qué lugar de trabajo perteneces?`) %>% 
  mutate(area2 = NA) %>% 
  relocate(area2,.after = area1) %>% 
  mutate(`1. ¿Existen acciones o prácticas en Lactolac que contribuyan a una mejor cultura laboral? Comparte ejemplos` = as.character(`1. ¿Existen acciones o prácticas en Lactolac que contribuyan a una mejor cultura laboral? Comparte ejemplos`))

data5 <- read_sheet("1MtaNcJaJB-gE9B7pV7WWovLsbbz2m6tWgiCS5cr-vLQ") %>%   #Costa Rica
    mutate(pais = "Costa Rica",
         fecha = `Submitted at`- hours(6)) %>% 
  relocate(pais, .before = `Submitted at`) %>% 
  relocate(fecha, .after = `Submitted at`) %>% 
  rename("area1" = `A. ¿A qué dirección perteneces?`,
         "area3" = `B. ¿A qué área de trabajo perteneces?`,
         "area4" = `C. ¿A qué lugar de trabajo perteneces?`) %>% 
  mutate(area2 = NA) %>% 
  relocate(area2,.after = area1)

ultima_actualizacion <- Sys.time()

total_pais <- tibble(
  pais = c("El Salvador","Guatemala","Honduras","Nicaragua","Costa Rica"),
  total = c(1093,217,84,263,62)
)

full_data <- bind_rows(data1,data2,data3,data4,data5)

# principal <- principal %>% 
#   mutate(user_login = as.character(user_login),
#          user_pass = as.character(user_pass))

# data <- data %>% 
#   mutate(fecha = `Submitted at`- hours(6)) %>% 
#   relocate(fecha, .after = `Submitted at`)

# principal <- principal %>% 
#   left_join(select(data,ref,eval,fecha,`Submission ID`,genero,generacion,nivel_jerarquico,tiempo_laboral),
#             by="ref")
# 
# principal <- principal %>% 
#   mutate(estado = case_when(!is.na(`Submission ID`) ~ "Completado",
#                             .default = "Pendiente"))

#Renombrando demográficos
# Agregar más demos si es necesario para el contador
# principal <- principal %>% 
#   rename(genero = matches("1."),  # buscando por número de pregunta
#          generacion = matches("2."),
#          jerarquia = matches("3."),
#          tiempo_laboral = matches("4."),) 


respuestas_diario <- full_data %>% 
  mutate(dias = floor_date(fecha, "day")) %>% 
  group_by(dias) %>% 
  count() 

#Temas personalizados  ----------------------------------------
#Highcharts
tema_general_hc <- hc_theme_merge(
  hc_theme_elementary(),
  hc_theme(
    colors = c("#14213D","#E5E5E5","#FCA311","#298DB4","#29BEB4"),
    chart = list(
      backgroundColor = "#FFF",
      style = list(
          fontFamily = "Roboto",
          color = "#000000"),
      zoomType = "x"
    ),
    title = list(
        align = "left",
        style = list(
          fontFamily = "Roboto",
          color = "#000000",
          fontWeight = "bold")
    ),
    subtitle = list(
        align = "left",
        style = list(
          fontFamily = "Roboto",
          color = "#000000",
          fontWeight = "bold")
    )
  )
)


```


Home
========================================================================

Row: Tarjetas {data-height=150}
-----------------------------------------------------------------------


### Value Boxes {.no-title}


```{r Datos principales}

# respuestas_global <- principal %>% 
#   group_by(estado) %>% 
#   summarise(respuestas = n()) %>% 
#   mutate(prop = round(respuestas/sum(respuestas)*100,0))

#Datos para MoE
# respuestas_totales <- count(principal[which(principal$estado=="Completado"),])

respuestas_totales <- count(full_data)

margen_error_pct <- function(n, N = NULL, p = 0.5, nivel_conf = 0.95) {
  z <- qnorm(1 - (1 - nivel_conf) / 2)
  me <- z * sqrt((p * (1 - p)) / n)
  
  if (!is.null(N)) {
    me <- me * sqrt((N - n) / (N - 1))
  }
  return(me * 100)
}

moe <- round(margen_error_pct( respuestas_totales, 
                       N = sum(total_pais$total)),digits = 2)

layout_column_wrap(
  width = 1/4,
  height = 140,
  gap = 5, #Espacio entre card de elementos en px
  value_box(
    h1("Población Regional", style = "font-size: 18px; font-weight: bold; font-family: Roboto;"),
    value = formatC(sum(total_pais$total),big.mark = ","),
    showcase = bs_icon("people-fill"),
    theme = value_box_theme(bg = "#FFF", fg = "#29BEB4")),
  value_box(
    h1("Respuestas Regionales", style = "font-size: 18px; font-weight: bold; font-family: Roboto;"),
    value = formatC(respuestas_totales$n,big.mark = ","),
    showcase = bs_icon("person-fill-check"),
    theme = value_box_theme(bg = "#FFF", fg = "#29BEB4")),
  value_box(
    h1("Avance", style = "font-size: 18px; font-weight: bold; font-family: Roboto;"),
    value = paste(round(respuestas_totales$n / sum(total_pais$total)*100,2),"%"),
    showcase = bs_icon("stars"),
    theme = value_box_theme(bg = "#FFF", fg = "#29BEB4")),
    value_box(
    h1("MoE 95%CL", style = "font-size: 18px; font-weight: bold; font-family: Roboto;"),
    value = paste(moe$n,"%"),
    showcase = bs_icon("clipboard-pulse"),
    theme = value_box_theme(bg = "#FFF", fg = "#29BEB4"))
)


```


Row: Respuestas {data-height=420}
-----------------------------------------------------------------------


```{r Respuestas diarias}

respuestas_diario_paises <- full_data %>% 
  mutate(dias = floor_date(fecha, "day")) %>% 
  group_by(pais,dias) %>% 
  count() 

layout_column_wrap(
  width = 1,
  height = 410,
  navset_card_pill(
  full_screen = TRUE,
  title = tags$div("Tendencia diaria", style = "font-size: 16px; padding-top: 2px; padding-bottom: 2px;"),
  nav_panel(
    title = tags$div("Global", style = "font-size: 16px; padding-top: 2px; padding-bottom: 2px;"), 
    respuestas_diario %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n), name = "Respuestas") %>%
      hc_title(text = "Respuestas Global") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 3,
        # states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="{point.y:.0f}")
      )) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ),
  nav_panel(
    title = tags$div("Por País", style = "font-size: 16px; padding-top: 2px; padding-bottom: 2px;"), 
    respuestas_diario_paises %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = pais)) %>%
      hc_title(text = "Respuestas por Países") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 3,
        # states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="{point.y:.0f}")
      )) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  )
  )
)


```


Row {data-height=420}
-----------------------------------------------------------------------

```{r respuestas por Genero Calculos, include=FALSE}

genero_global <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  fillable = TRUE,
  gap = 2,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>%
      # filter(estado=="Completado") %>% 
      group_by(genero) %>%
      count() %>% 
      ungroup() %>% 
      hchart(type="pie",hcaes(x=genero,y=n),name="Género") %>% 
      hc_title(text="Respuestas por Género")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      # filter(estado=="Completado") %>% 
      group_by(floor_date(fecha, "day"),genero) %>%
      count() %>% 
      rename("dias"=1) %>% 
      ungroup() %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = genero)) %>%
      hc_title(text = "Respuestas por Género") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

genero_elsalvador <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,genero) %>% 
      count() %>% 
      filter(pais =="El Salvador") %>% 
      hchart(type="pie",hcaes(x=genero,y=n),name="Género") %>% 
      hc_title(text="Respuestas por Género El Salvador")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,genero) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="El Salvador") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = genero)) %>%
      hc_title(text = "Respuestas por Género El Salvador") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

genero_guatemala <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,genero) %>% 
      count() %>% 
      filter(pais =="Guatemala") %>% 
      hchart(type="pie",hcaes(x=genero,y=n),name="Género") %>% 
      hc_title(text="Respuestas por Género Guatemala")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,genero) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Guatemala") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = genero)) %>%
      hc_title(text = "Respuestas por Género Guatemala") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

genero_honduras <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,genero) %>% 
      count() %>% 
      filter(pais =="Honduras") %>% 
      hchart(type="pie",hcaes(x=genero,y=n),name="Género") %>% 
      hc_title(text="Respuestas por Género Honduras")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,genero) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Honduras") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = genero)) %>%
      hc_title(text = "Respuestas por Género Honduras") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

genero_nicaragua <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,genero) %>% 
      count() %>% 
      filter(pais =="Nicaragua") %>% 
      hchart(type="pie",hcaes(x=genero,y=n),name="Género") %>% 
      hc_title(text="Respuestas por Género Nicaragua")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,genero) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Nicaragua") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = genero)) %>%
      hc_title(text = "Respuestas por Género Nicaragua") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

genero_costarica <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,genero) %>% 
      count() %>% 
      filter(pais =="Costa Rica") %>% 
      hchart(type="pie",hcaes(x=genero,y=n),name="Género") %>% 
      hc_title(text="Respuestas por Género Costa Rica")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,genero) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Costa Rica") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = genero)) %>%
      hc_title(text = "Respuestas por Género Costa Rica") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)


```



```{r Respuestas por Genero }

navset_card_pill(
  title = tags$div("Respuestas por Género", style = "font-size: 16px; padding-top: 2px; padding-bottom: 2px;"),
  nav_panel(title = "Global",
            genero_global
  ),
  nav_menu(title = "Países",
    nav_panel(title = "Guatemala",
            genero_guatemala),
    nav_panel(title = "El Salvador",
            genero_elsalvador),
    nav_panel(title = "Honduras",
            genero_honduras),
    nav_panel(title = "Nicaragua",
            genero_nicaragua),
    nav_panel(title = "Costa Rica",
            genero_costarica)
))


```


Row {data-height=420}
-----------------------------------------------------------------------

```{r respuestas por Jerarquia Calculos, include=FALSE}

jerarquia_global <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  fillable = TRUE,
  gap = 2,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>%
      # filter(estado=="Completado") %>% 
      group_by(nivel_jerarquico) %>%
      count() %>% 
      ungroup() %>% 
      hchart(type="pie",hcaes(x=nivel_jerarquico,y=n),name="Nivel Jerárquico") %>% 
      hc_title(text="Respuestas por Nivel Jerárquico")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      # filter(estado=="Completado") %>% 
      group_by(floor_date(fecha, "day"),nivel_jerarquico) %>%
      count() %>% 
      rename("dias"=1) %>% 
      ungroup() %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = nivel_jerarquico)) %>%
      hc_title(text = "Respuestas por Nivel Jerárquico") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

jerarquia_elsalvador <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,nivel_jerarquico) %>% 
      count() %>% 
      filter(pais =="El Salvador") %>% 
      hchart(type="pie",hcaes(x=nivel_jerarquico,y=n),name="Nivel Jerárquico") %>% 
      hc_title(text="Respuestas por Nivel Jerárquico El Salvador")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,nivel_jerarquico) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="El Salvador") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = nivel_jerarquico)) %>%
      hc_title(text = "Respuestas por Nivel Jerárquico El Salvador") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

jerarquia_guatemala <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,nivel_jerarquico) %>% 
      count() %>% 
      filter(pais =="Guatemala") %>% 
      hchart(type="pie",hcaes(x=nivel_jerarquico,y=n),name="Nivel Jerárquico") %>% 
      hc_title(text="Respuestas por Nivel Jerárquico Guatemala")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,nivel_jerarquico) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Guatemala") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = nivel_jerarquico)) %>%
      hc_title(text = "Respuestas por Nivel Jerárquico Guatemala") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

jerarquia_honduras <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,nivel_jerarquico) %>% 
      count() %>% 
      filter(pais =="Honduras") %>% 
      hchart(type="pie",hcaes(x=nivel_jerarquico,y=n),name="Nivel Jerárquico") %>% 
      hc_title(text="Respuestas por Nivel Jerárquico Honduras")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,nivel_jerarquico) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Honduras") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = nivel_jerarquico)) %>%
      hc_title(text = "Respuestas por Nivel Jerárquico Honduras") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

jerarquia_nicaragua <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,nivel_jerarquico) %>% 
      count() %>% 
      filter(pais =="Nicaragua") %>% 
      hchart(type="pie",hcaes(x=nivel_jerarquico,y=n),name="Nivel Jerárquico") %>% 
      hc_title(text="Respuestas por Nivel Jerárquico Nicaragua")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,nivel_jerarquico) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Nicaragua") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = nivel_jerarquico)) %>%
      hc_title(text = "Respuestas por Nivel Jerárquico Nicaragua") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

jerarquia_costarica <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,nivel_jerarquico) %>% 
      count() %>% 
      filter(pais =="Costa Rica") %>% 
      hchart(type="pie",hcaes(x=nivel_jerarquico,y=n),name="Nivel Jerárquico") %>% 
      hc_title(text="Respuestas por Nivel Jerárquico Costa Rica")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,nivel_jerarquico) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Costa Rica") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = nivel_jerarquico)) %>%
      hc_title(text = "Respuestas por Nivel Jerárquico Costa Rica") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)


```


```{r Respuestas por Jerarquia }

navset_card_pill(
  title = tags$div("Respuestas por Jerarquía", style = "font-size: 16px; padding-top: 2px; padding-bottom: 2px;"),
  nav_panel(title = "Global",
            jerarquia_global
  ),
  nav_menu(title = "Países",
    nav_panel(title = "Guatemala",
            jerarquia_guatemala),
    nav_panel(title = "El Salvador",
            jerarquia_elsalvador),
    nav_panel(title = "Honduras",
            jerarquia_honduras),
    nav_panel(title = "Nicaragua",
            jerarquia_nicaragua),
    nav_panel(title = "Costa Rica",
            jerarquia_costarica)
))

```


Row {data-height=420}
-----------------------------------------------------------------------

```{r respuestas por Tiempo Laboral Calculos, include=FALSE}

tlaboral_global <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  fillable = TRUE,
  gap = 2,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>%
      # filter(estado=="Completado") %>% 
      group_by(tiempo_laboral) %>%
      count() %>% 
      ungroup() %>% 
      hchart(type="pie",hcaes(x=tiempo_laboral,y=n),name="Tiempo de Trabajo") %>% 
      hc_title(text="Respuestas por Tiempo de Trabajo")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      # filter(estado=="Completado") %>% 
      group_by(floor_date(fecha, "day"),tiempo_laboral) %>%
      count() %>% 
      rename("dias"=1) %>% 
      ungroup() %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = tiempo_laboral)) %>%
      hc_title(text = "Respuestas por Tiempo de Trabajo") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)

  ))
)

tlaboral_elsalvador <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,tiempo_laboral) %>% 
      count() %>% 
      filter(pais =="El Salvador") %>% 
      hchart(type="pie",hcaes(x=tiempo_laboral,y=n),name="Tiempo de Trabajo") %>% 
      hc_title(text="Respuestas por Tiempo de Trabajo El Salvador")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,tiempo_laboral) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="El Salvador") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = tiempo_laboral)) %>%
      hc_title(text = "Respuestas por Tiempo de Trabajo El Salvador") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

tlaboral_guatemala <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,tiempo_laboral) %>% 
      count() %>% 
      filter(pais =="Guatemala") %>% 
      hchart(type="pie",hcaes(x=tiempo_laboral,y=n),name="Tiempo de Trabajo") %>% 
      hc_title(text="Respuestas por Tiempo de Trabajo Guatemala")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,tiempo_laboral) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Guatemala") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = tiempo_laboral)) %>%
      hc_title(text = "Respuestas por Tiempo de Trabajo Guatemala") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

tlaboral_honduras <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,tiempo_laboral) %>% 
      count() %>% 
      filter(pais =="Honduras") %>% 
      hchart(type="pie",hcaes(x=tiempo_laboral,y=n),name="Tiempo de Trabajo") %>% 
      hc_title(text="Respuestas por Tiempo de Trabajo Honduras")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,tiempo_laboral) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Honduras") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = tiempo_laboral)) %>%
      hc_title(text = "Respuestas por Tiempo de Trabajo Honduras") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

tlaboral_nicaragua <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,tiempo_laboral) %>% 
      count() %>% 
      filter(pais =="Nicaragua") %>% 
      hchart(type="pie",hcaes(x=tiempo_laboral,y=n),name="Tiempo de Trabajo") %>% 
      hc_title(text="Respuestas por Tiempo de Trabajo Nicaragua")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,tiempo_laboral) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Nicaragua") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = tiempo_laboral)) %>%
      hc_title(text = "Respuestas por Tiempo de Trabajo Nicaragua") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

tlaboral_costarica <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,tiempo_laboral) %>% 
      count() %>% 
      filter(pais =="Costa Rica") %>% 
      hchart(type="pie",hcaes(x=tiempo_laboral,y=n),name="Tiempo de Trabajo") %>% 
      hc_title(text="Respuestas por Tiempo de Trabajo Costa Rica")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,tiempo_laboral) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Costa Rica") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = tiempo_laboral)) %>%
      hc_title(text = "Respuestas por Tiempo de Trabajo Costa Rica") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)


```


```{r Respuestas por Tiempo Laboral}

navset_card_pill(
  title = tags$div("Respuestas por Tiempo de Trabajo", style = "font-size: 16px; padding-top: 2px; padding-bottom: 2px;"),
  nav_panel(title = "Global",
            tlaboral_global
  ),
  nav_menu(title = "Países",
    nav_panel(title = "Guatemala",
            tlaboral_guatemala),
    nav_panel(title = "El Salvador",
            tlaboral_elsalvador),
    nav_panel(title = "Honduras",
            tlaboral_honduras),
    nav_panel(title = "Nicaragua",
            tlaboral_nicaragua),
    nav_panel(title = "Costa Rica",
            tlaboral_costarica)
))

```


Row {data-height=420}
-----------------------------------------------------------------------

```{r respuestas por Generacion Calculos, include=FALSE}

generacion_global <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  fillable = TRUE,
  gap = 2,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>%
      # filter(estado=="Completado") %>% 
      group_by(generacion) %>%
      count() %>% 
      ungroup() %>% 
      hchart(type="pie",hcaes(x=generacion,y=n),name="Generación") %>% 
      hc_title(text="Respuestas por Generación")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      # filter(estado=="Completado") %>% 
      group_by(floor_date(fecha, "day"),generacion) %>%
      count() %>% 
      rename("dias"=1) %>% 
      ungroup() %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = generacion)) %>%
      hc_title(text = "Respuestas por Generación") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)

  ))
)

generacion_elsalvador <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,generacion) %>% 
      count() %>% 
      filter(pais =="El Salvador") %>% 
      hchart(type="pie",hcaes(x=generacion,y=n),name="Generación") %>% 
      hc_title(text="Respuestas por Generación El Salvador")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,generacion) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="El Salvador") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = generacion)) %>%
      hc_title(text = "Respuestas por Generación El Salvador") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

generacion_guatemala <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,generacion) %>% 
      count() %>% 
      filter(pais =="Guatemala") %>% 
      hchart(type="pie",hcaes(x=generacion,y=n),name="Generación") %>% 
      hc_title(text="Respuestas por Generación Guatemala")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,generacion) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Guatemala") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = generacion)) %>%
      hc_title(text = "Respuestas por Generación Guatemala") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

generacion_honduras <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,generacion) %>% 
      count() %>% 
      filter(pais =="Honduras") %>% 
      hchart(type="pie",hcaes(x=generacion,y=n),name="Generación") %>% 
      hc_title(text="Respuestas por Generación Honduras")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,generacion) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Honduras") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = generacion)) %>%
      hc_title(text = "Respuestas por Generación Honduras") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

generacion_nicaragua <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,generacion) %>% 
      count() %>% 
      filter(pais =="Nicaragua") %>% 
      hchart(type="pie",hcaes(x=generacion,y=n),name="Generación") %>% 
      hc_title(text="Respuestas por Generación Nicaragua")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,generacion) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Nicaragua") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = generacion)) %>%
      hc_title(text = "Respuestas por Generación Nicaragua") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)

generacion_costarica <- layout_column_wrap(
  width = NULL,
  style = css(grid_template_columns = "1fr 2fr"),
  height = 410,
  card(
    full_screen = TRUE,
    card_body(
      full_data %>% 
      group_by(pais,generacion) %>% 
      count() %>% 
      filter(pais =="Costa Rica") %>% 
      hchart(type="pie",hcaes(x=generacion,y=n),name="Generación") %>% 
      hc_title(text="Respuestas por Generación Costa Rica")%>%
      # hc_subtitle(text="") %>%
      hc_plotOptions(pie=list(
        innerSize="55%",
        tooltip=list(pointFormat="{point.y:,.0f} ({point.percentage:.0f}%)"),
        dataLabels=list(enabled=TRUE,
                        format="{point.name}</br>{point.y:,.0f} ({point.percentage:.0f}%)"))
        )%>%
      hc_yAxis(title=list(text=""))%>%
      hc_xAxis(title=list(text=""))%>%
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled=TRUE)
  )),
  card(
    full_screen = TRUE,
    card_body(
     full_data %>%
      group_by(dias= floor_date(fecha, "day"),pais,generacion) %>%
      count() %>% 
      ungroup() %>% 
      filter(pais =="Costa Rica") %>% 
      mutate(tiempo = dias %>% datetime_to_timestamp()) %>% 
      hchart("spline", hcaes(x = tiempo, y = n, group = generacion)) %>%
      hc_title(text = "Respuestas por Generación Costa Rica") %>%
      hc_subtitle(text = "Tendencia diaria") %>% 
      hc_xAxis(type = "datetime", labels = list(format = "{value:%d-%b}"), title = list(text = "")) %>% 
      hc_yAxis(title = list(text = "Cantidad de Respuestas")) %>%
      hc_plotOptions(spline = list(
        lineWidth = 2,
        states = list(hover = list(lineWidth = 5)), #resalta la linea al pasar el mouse
        marker = list(enabled = FALSE),
        dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.y:.0f}</span>"))
        ) %>% 
      hc_add_theme(tema_general_hc) %>% 
      hc_exporting(enabled = TRUE)
  ))
)


```


```{r Respuestas por Generacion}

navset_card_pill(
  title = tags$div("Respuestas por Generación", style = "font-size: 16px; padding-top: 2px; padding-bottom: 2px;"),
  nav_panel(title = "Global",
            generacion_global
  ),
  nav_menu(title = "Países",
    nav_panel(title = "Guatemala",
            generacion_guatemala),
    nav_panel(title = "El Salvador",
            generacion_elsalvador),
    nav_panel(title = "Honduras",
            generacion_honduras),
    nav_panel(title = "Nicaragua",
            generacion_nicaragua),
    nav_panel(title = "Costa Rica",
            generacion_costarica)
))

```


Row {data-height=450}
-----------------------------------------------------------------------


```{r Avance por Pais}


contador_pais <- full_data %>% 
  group_by(pais) %>% 
  summarise(completado = n(), .groups = "drop") %>% 
  left_join(total_pais, by = "pais") %>% 
  mutate(pendiente = total - completado) %>% 
  mutate(prop_completado = round(completado/total*100,0),
         prop_pendiente = round(pendiente/total*100,0)) %>% 
  mutate(moe = round(margen_error_pct(completado, 
                       N = total),digits = 2))

layout_column_wrap(
  width = 1,
  height = 440,
  card(
  full_screen = TRUE,
  card_body(
   contador_pais %>% 
    hchart("bar", hcaes(x = pais, y = 100, z = total, moe = moe), name = "Población", showInLegend = TRUE,
           borderRadius = 10,
           dataLabels=list(enabled=TRUE, format="{point.z:.0f}"),
           tooltip = list(pointFormat = "<span style='color:{point.color}'>●</span> {series.name}: <b>{point.z:,.0f}
               ({point.y:.0f}%)</b>")) %>%
    hc_add_series(type = "bar",data = contador_pais,hcaes(x = pais, y = prop_completado, z = completado),
                  name = "Completado", color = "#29BEB4",showInLegend = TRUE,
                  borderRadius = 10,
                  dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.z:.0f} ({point.y:.0f}%)</span>"),
                  tooltip = list(pointFormat = "<span style='color:{point.color}'>●</span> {series.name}: <b>{point.z:,.0f}
               ({point.y:.0f}%)</b> <br> MoE: <b>{point.moe:.0f}% </b>"))  %>%
    hc_title(text = "Avance de Respuestas por País") %>%
    # hc_subtitle(text = "Frecuencias por Nivel de Respuesta") %>%
    hc_xAxis(title = list(text = "")) %>% 
    hc_yAxis(title = list(text = "Porcentaje"),ceiling = 100, labels = list(format = "{text}%")) %>%
    hc_colors(c("#EBEBEB"))%>%
    hc_plotOptions(bar=list(
      grouping = FALSE, 
      # pointPadding = 0,      # SUPERPOSICIÓN TOTAL
      pointPlacement = 0    # MISMA POSICIÓN EXACTA
      # groupPadding = 0,      # MISMO GRUPO (sin separación)
    )) %>%
    # hc_tooltip(pointFormat = "<span style='color:{point.color}'>●</span> {series.name}: <b>{point.z:,.0f}
    #            ({point.y:.0f}%)</b> <br> MoE: <b>{point.moe:.0f}% </b>") %>% 
    hc_scrollbar(enabled = TRUE) %>% 
    hc_add_theme(tema_general_hc) %>% 
    hc_exporting(enabled = TRUE)
  ))
)

```


Row {data-height=450}
-----------------------------------------------------------------------


```{r Avance por Direccion}

principal_area1 <- read_sheet("1d33PzU6NBnrB-dJGP84zkKA0G5UryoRVSVF1a5NOIYU",sheet = "area1") 

avance_area1 <- full_data %>% 
  group_by(pais,area1) %>% 
  summarise(completado = n(), .groups = "drop") %>% 
  mutate(key = paste0(pais," - ",area1))

contador_area1 <- principal_area1 %>% 
  left_join(
    avance_area1 %>% 
      select(key,completado),
    by = "key"
  ) %>% 
  mutate(pendiente = total - completado) %>% 
  mutate(prop_completado = round(completado/total*100,0),
         prop_pendiente = round(pendiente/total*100,0)) %>% 
  mutate(moe = round(margen_error_pct(completado, 
                       N = total),digits = 2))

layout_column_wrap(
  width = 1,
  height = 440,
  card(
  full_screen = TRUE,
  card_body(
   contador_area1 %>% 
    hchart("bar", hcaes(x = key, y = 100, z = total, moe = moe), name = "Población", showInLegend = TRUE,
           borderRadius = 10,
           dataLabels=list(enabled=TRUE, format="{point.z:.0f}"),
           tooltip = list(pointFormat = "<span style='color:{point.color}'>●</span> {series.name}: <b>{point.z:,.0f}
               ({point.y:.0f}%)</b>")) %>%
    hc_add_series(type = "bar",data = contador_area1,hcaes(x = key, y = prop_completado, z = completado),
                  name = "Completado", color = "#29BEB4",showInLegend = TRUE,
                  borderRadius = 10,
                  dataLabels=list(enabled=TRUE, format="<span style='color:{series.color}'>{point.z:.0f} ({point.y:.0f}%)</span>"),
                  tooltip = list(pointFormat = "<span style='color:{point.color}'>●</span> {series.name}: <b>{point.z:,.0f}
               ({point.y:.0f}%)</b>"))  %>%
    hc_title(text = "Avance de Respuestas por Dirección") %>%
    # hc_subtitle(text = "Frecuencias por Nivel de Respuesta") %>%
    hc_xAxis(title = list(text = "")) %>% 
    hc_yAxis(title = list(text = "Porcentaje"),ceiling = 100, labels = list(format = "{text}%")) %>%
    hc_colors(c("#EBEBEB"))%>%
    hc_plotOptions(bar=list(
      grouping = FALSE, 
      # pointPadding = 0,      # SUPERPOSICIÓN TOTAL
      pointPlacement = 0    # MISMA POSICIÓN EXACTA
      # groupPadding = 0,      # MISMO GRUPO (sin separación)
    )) %>%
    # hc_tooltip(pointFormat = "<span style='color:{point.color}'>●</span> {series.name}: <b>{point.z:,.0f}
    #            ({point.y:.0f}%)</b> <br> MoE: <b>{point.moe:.0f}% </b>") %>% 
    hc_scrollbar(enabled = TRUE) %>% 
    hc_add_theme(tema_general_hc) %>% 
    hc_exporting(enabled = TRUE)
  ))
)

```


Row {data-height=12}
-----------------------------------------------------------------------

<div style="display:flex; justify-content:space-between; align-items:center;
            width:100%; margin-top:4px; margin-bottom:4px;">

  <!-- Izquierda -->
  <p style="background:transparent; padding:4px; border-radius:6px;
            font-size:10px; color:#003366; margin:0;">
    Powered by 
    <a href="https://insightdap.com/" target="_blank"
       style="color:#003366; font-weight:bold; text-decoration:none;">
      Insight Data Analytics Partners®
    </a>
  </p>

  <!-- Derecha -->
  <p style="background:transparent; padding:4px; border-radius:6px;
            font-size:10px; color:#003366; margin:0; text-align:right;">
    <b>Última actualización:</b>
   `r format(ultima_actualizacion, "%d-%m-%Y %H:%M",tz = "America/El_Salvador")`
  </p>

</div>



Áreas
========================================================================

Row {data-height=550}
-----------------------------------------------------------------------

```{r}

#Renombre de variables
# full_data <- full_data %>% 
#   rename("area1" = `A. ¿A qué dirección perteneces?`,
#          "area2" = `B. ¿A qué departamento perteneces?`,
#          "area3" = `C. ¿A qué centro de costo perteneces?`,
#          "area4" = `D. ¿A qué lugar de trabajo perteneces?`)


card(
  full_screen = TRUE,
  style = "width: 100%;",
  height = 520,
  card_body(
    div(
      class = "title_reactable",
      h3("Respuestas por Dirección y Área de Trabajo"),
      full_data %>% 
        group_by(pais,area1, area3) %>% 
        summarise(respuestas = n(), .groups = "drop") %>% 
        reactable(
          highlight = TRUE,
          showPageSizeOptions = TRUE,
          pageSizeOptions = c(20,40,60,80),
          defaultPageSize = 20,
          groupBy = "pais",
          searchable = TRUE,
          columns = list(
            pais = colDef(name = "País"),
            area1 = colDef(name = "Dirección"),
            area3 = colDef(name = "Área de Trabajo"),
            respuestas = colDef(name = "Respuestas",
                                aggregate = "sum",
                                format = colFormat(sep = TRUE,locales = "en-US"),
                                footer = function(values) prettyNum(sprintf("%.0f",sum(values)),
                                                                               big.mark = ","))
          ),
          theme = reactableTheme(
            highlightColor = "#CCE0FF",
            headerStyle = list(fontSize="14px"),
            cellStyle = list(fontSize="12px"),
            style = list(fontFamily = "Nunito")
             ),
          class = "packages-table",
        )
  )
))


```



Row {data-height=12}
-----------------------------------------------------------------------

<div style="display:flex; justify-content:space-between; align-items:center;
            width:100%; margin-top:4px; margin-bottom:4px;">

  <!-- Izquierda -->
  <p style="background:transparent; padding:4px; border-radius:6px;
            font-size:10px; color:#003366; margin:0;">
    Powered by 
    <a href="https://insightdap.com/" target="_blank"
       style="color:#003366; font-weight:bold; text-decoration:none;">
      Insight Data Analytics Partners®
    </a>
  </p>

  <!-- Derecha -->
  <p style="background:transparent; padding:4px; border-radius:6px;
            font-size:10px; color:#003366; margin:0; text-align:right;">
    <b>Última actualización:</b>
   `r format(ultima_actualizacion, "%d-%m-%Y %H:%M",tz = "America/El_Salvador")`
  </p>

</div>
